name: Update data
on:
  workflow_dispatch:
    inputs:
      add_words:
        description: "Array of words to be added."
        type: string
      remove_words:
        description: "Array of words to be removed."
        type: string
      add_verbs:
        description: "Array of verbs to be added."
        type: string
      remove_verbs:
        description: "Array of verbs to be removed."
        type: string

jobs:
  update-data:
    runs-on: ubuntu-latest
    name: "Update data"
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v6
      
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
      
      - name: Update data
        run: node .github/update-data.mjs
        env:
          ADD_WORDS: ${{ github.event.inputs.add_words }}
          REMOVE_WORDS: ${{ github.event.inputs.remove_words }}
          ADD_VERBS: ${{ github.event.inputs.add_verbs }}
          REMOVE_VERBS: ${{ github.event.inputs.remove_verbs }}
      
      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "feat: update data"
          git push